# PaddleSpeech API 配置文件

# 启动配置
server:
  ip: "0.0.0.0"
  port: 8091

# mqtt配置
mqtt_server:
  base_url: "http://124.71.81.97:18007"
  key: "ZhuoShang"


# 音频分类检测服务配置
cls_config:
  ip: "127.0.0.1"
  port: 8090
  topk: 3
  temp_dir: "/workspace/temp"
  sample_rate: 16000
  score: 0.35
  labels:
    Shout-呼喊
    Bellow-咆哮
    Yell-叫喊
    Screaming-尖叫
    Crying-哭泣
    Sneeze-打喷嚏
    Slam-猛击
    Explosion-爆炸
    Boom-轰鸣
    Glass-玻璃破碎
    Chink-碰撞声
    Bang-爆裂声
    Breaking-破碎声
    Squeal-尖叫声
    Cough-咳嗽



# Sherpa TTS 配置
sherpa_tts:
  acoustic_model_dirname: "matcha-icefall-zh-en"
  vocoder_filename: "vocos-16khz-univ.onnx"
  num_threads: 2
  speed: 1.0
  sid: 0

# TTS 输出目录
tts_output_dir: "/workspace/PaddleSpeech-api/audiofile"

# app服务器
app_server:
  base_url: "http://182.61.31.25:9001"


